### ISSUE TITLE
Extremely long training time

### ISSUE THREAD

**Issue by spaceinmind** [SukiYume/DRAFTS#2]
Dear DRAFTS developers,

I am facing the issue of an extremely long training time for the detection model.
When I tried running
`python binary_train.py resnet18 BinaryNet`
It takes > 30 mins for just one epoch to complete training.
Is this time normal? Is there any way I can make it faster?
Thank you.

Best regards,
Simon Ho

**Comment by spaceinmind** [comment]
I found out you can increase the number in `num_workers` in `centernet_train.py` to speed up the training process:
```
    train_loader = torch.utils.data.DataLoader(train_data, batch_size=batch_size, shuffle=True, num_workers=8, pin_memory=True)
    val_loader   = torch.utils.data.DataLoader(val_data,   batch_size=batch_size, shuffle=True, num_workers=8, pin_memory=True)
```

**Comment by spaceinmind** [comment]
I found out you can increase the number in `num_workers` in `centernet_train.py` to speed up the training process:
```
    train_loader = torch.utils.data.DataLoader(train_data, batch_size=batch_size, shuffle=True, num_workers=8, pin_memory=True)
    val_loader   = torch.utils.data.DataLoader(val_data,   batch_size=batch_size, shuffle=True, num_workers=8, pin_memory=True)
```

**Comment by SukiYume** [comment]
The training data for the binary classification model in DRAFTS underwent random RFI augmentation and random data merging (randomly combining 1-5 data samples). These randomization processes can take up a significant amount of training time.

If you are training on a Windows system, please set `num_workers` to 0 (since the implementation of multiprocessing on Windows differs from Linux). If you have access to a powerful Linux server, it's recommended to increase `num_workers` as much as possible. Generally, setting `num_workers` to a value equal to the `batch_size` or half of it can optimize computational efficiency. Additionally, setting `pin_memory` to `True` can speed up training starting from the second epoch.
